/**
 * Updates project descriptions in MongoDB with formatted HTML.
 * Run:  npx tsx scripts/update-descriptions.ts
 */
import { readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { PrismaClient } from "../generated/prisma";

function loadMongoUri(): string {
  const envPath = resolve(process.cwd(), ".env");
  if (existsSync(envPath)) {
    const raw = readFileSync(envPath, "utf8");
    for (const line of raw.split("\n")) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const eq = trimmed.indexOf("=");
      if (eq === -1) continue;
      const key = trimmed.slice(0, eq).trim();
      let val = trimmed.slice(eq + 1).trim();
      if (
        (val.startsWith('"') && val.endsWith('"')) ||
        (val.startsWith("'") && val.endsWith("'"))
      ) {
        val = val.slice(1, -1);
      }
      if (key === "MONGODB_URI") return val;
    }
  }
  const fromEnv = process.env.MONGODB_URI;
  if (fromEnv) return fromEnv;
  throw new Error("MONGODB_URI not found.");
}

const descriptions: Record<string, string> = {
  "Lineup Legends": `<p>Lineup Legends is a full-stack fantasy basketball platform where users build their dream lineup under a <strong>$15 salary cap</strong>. Create lineups, rate and compete against others, and engage with a passionate community of basketball fans.</p>
<ul>
<li>Salary-cap lineup builder with positional constraints, drag-and-drop ordering, and a gamble system featuring animations, sound effects, and confetti</li>
<li>Multi-factor authentication supporting TOTP, email codes, and WebAuthn passkeys with encrypted secrets and Redis-backed session verification</li>
<li>Social layer including follows, threaded comments, upvote/downvote voting, Giphy GIF embeds, bookmarks, and automated profanity filtering</li>
<li>Cache-Aside strategy with Redis to cache high-traffic public data, reducing database load and improving page load times</li>
<li>File uploads to S3 with CloudFront CDN delivery, MIME-type validation, and integrated YouTube Data API for curated video content</li>
<li>Admin dashboard with user management, ban/suspend enforcement, flagged content review, and player request queue with community value voting</li>
</ul>
<p><strong>Guest login</strong></p>
<ul>
<li>USERNAME: guest</li>
<li>EMAIL: llguest@gmail.com</li>
<li>PASSWORD: 123</li>
</ul>
<p><em>For the best experience, sign in with Google.</em></p>`,

  "Sommelier Circle": `<p>A full-stack MERN application designed to foster a vibrant online wine community. Users can create and manage blog posts, connect with other wine enthusiasts, and explore an extensive wine encyclopedia.</p>
<ul>
<li>Rich text blog editor powered by Quill for creating and managing community posts</li>
<li>Inverted index with fuzzy search for an enhanced experience when exploring wines, critics, and wine-related events</li>
<li>Google Places API integration for tailored wine location suggestions and nearby venue discovery</li>
<li>Autocomplete feature for fast and efficient venue search</li>
<li>Follow system, community interactions, and participation in wine-related events</li>
</ul>
<p><em>All content, including images and descriptions, is for demonstration purposes only.</em></p>`,

  "Place of Grace Inc": `<p>A production website built for a care home facility serving developmentally disabled adults in Northern California. Provides essential information for families, potential staff, and the community.</p>
<ul>
<li>About pages, staff directory, mission page, careers page, and contact forms</li>
<li>Forms routed to specific staff members via the Microsoft Graph API</li>
<li>OAuth-based authentication for secure API communication</li>
<li>Hands-on experience with DNS configuration, SEO optimization, and cloud infrastructure</li>
</ul>`,

  "Memory Squares": `<p>A memory game inspired by Nickelodeon's Brain Surge where players replicate a sequence of flashing squares generated by the CPU. Difficulty scales with each level through increased grid size and speed.</p>
<ul>
<li>CPU-generated sequences stored in arrays, compared against player input on submission</li>
<li>Progressive difficulty with expanding grid size and shorter display windows</li>
<li>Timer-based challenge mode for added pressure</li>
<li>High scores persisted in local storage with automatic leaderboard updates</li>
<li>Audio-visual feedback for correct and incorrect answers</li>
</ul>`,

  "Curate Sphere": `<p>A PERN stack (PostgreSQL, Express, React, Node.js) application that leverages the Harvard Art Museums API, allowing users to create and manage their own art exhibitions from curated artworks.</p>
<ul>
<li>Complex search filtering across the Harvard Art Museums catalog</li>
<li>Advanced state management for exhibition curation workflows</li>
<li>Custom caching system integration to reduce API calls and improve performance</li>
<li>Customizable user profiles with personal exhibition galleries</li>
<li>End-to-end testing and robust error handling throughout the application</li>
</ul>`,

  LibrisList: `<p>A modern web application that simplifies how users discover, manage, and engage with their reading material. Built with Next.js 15 and the App Router for optimized rendering and streamlined routing.</p>
<ul>
<li>Google Books API integration with advanced search filters and detailed book information</li>
<li>Auth.js implementation for secure Google Sign-In with personalized user experiences</li>
<li>Supabase (PostgreSQL) backend for storing curated reading lists, notes, and user preferences</li>
<li>Responsive design with Tailwind CSS for a clean, modern interface across all devices</li>
<li>Full-stack architecture demonstrating RESTful API integration and robust authentication practices</li>
</ul>`,

  "Internal War": `<p>A custom headless eCommerce storefront built for a streetwear brand using <strong>Shopify Hydrogen Remix</strong>. Delivers a high-performance shopping experience with a fully customized brand aesthetic.</p>
<ul>
<li>GraphQL-powered data fetching for efficient store data management</li>
<li>Shopify Admin configuration for collections, products, and navigation</li>
<li>Fully customized storefront aligned with brand identity and design requirements</li>
<li>High-performance architecture optimized for fast page loads and smooth checkout</li>
</ul>
<p><em>Near production — awaiting final content and design approval from the client.</em></p>`,

  "Athlete 2 Athlete": `<p>A full-stack platform connecting athletes, coaches, and the community through athlete spotlights, testimonials, and admin-controlled user submissions.</p>
<ul>
<li>Athlete spotlights with background, achievements, community impact, and up to three images stored on AWS S3</li>
<li>Testimonial submission system with admin approval workflow before publication</li>
<li>Admin dashboard with submission management, status controls, profile editing, and email notifications via Nodemailer</li>
<li>Redis caching to optimize API performance and reduce database load</li>
<li>Built with React, Tailwind CSS, Node.js, Express, PostgreSQL, Redis, and AWS S3</li>
</ul>
<p><em>No guest login available — please view the demo video to see admin features.</em></p>`,
};

async function main() {
  const uri = loadMongoUri();
  const prisma = new PrismaClient({
    datasources: { db: { url: uri } },
  });

  const projects = await prisma.project.findMany();
  let updated = 0;

  for (const p of projects) {
    const newDesc = descriptions[p.title];
    if (!newDesc) continue;
    await prisma.project.update({
      where: { id: p.id },
      data: { description: newDesc },
    });
    console.log(`Updated: "${p.title}"`);
    updated += 1;
  }

  console.log(`Done. ${String(updated)} description(s) updated.`);
  await prisma.$disconnect();
}

main().catch((e: unknown) => {
  console.error(e);
  process.exit(1);
});
